{% set name = "brainglobe-segmentation" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brainglobe-segmentation-{{ version }}.tar.gz
  sha256: 89533b7d8b160cae0d28a84384ab01e236c04f4f769db406c51faa6ea799a140

build:
  entry_points:
    - brainglobe-segmentation = brainglobe_segmentation.segment:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
  run:
    - brainglobe-napari-io >=0.3.0
    - dask-core >=2.15.0
    - imio
    - brainglobe-utils >=0.2.7
    - napari-plugin-engine >=0.1.4
    - napari >=0.4.5
    - numpy
    - pandas
    - pytables
    - python >=3.9
    - scikit-image

test:
  imports:
    - brainglobe_segmentation
  commands:
    - pip list
    - pip check
    # - brainglobe-segmentation --help  # This is opening the napari GUI and not closing
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/brainglobe-segmentation
  summary: Manual segmentation of 3D brain structures in a common anatomical space
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/brainglobe/brainglobe-segmentation

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
    - jaimergp
    - willGraham01
